# permissions for end users to view lokistacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lokistack-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: light-weight-loki-operator
    app.kubernetes.io/part-of: light-weight-loki-operator
    app.kubernetes.io/managed-by: kustomize
  name: lokistack-viewer-role
rules:
- apiGroups:
  - loki.lightweight.com
  resources:
  - lokistacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loki.lightweight.com
  resources:
  - lokistacks/status
  verbs:
  - get
