# permissions for end users to edit promtails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: promtail-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: light-weight-loki-operator
    app.kubernetes.io/part-of: light-weight-loki-operator
    app.kubernetes.io/managed-by: kustomize
  name: promtail-editor-role
rules:
- apiGroups:
  - loki.lightweight.com
  resources:
  - promtails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loki.lightweight.com
  resources:
  - promtails/status
  verbs:
  - get
