---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loki.grafana.com
  resources:
  - promtails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loki.grafana.com
  resources:
  - promtails/finalizers
  verbs:
  - update
- apiGroups:
  - loki.grafana.com
  resources:
  - promtails/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - loki.lightweight.com
  resources:
  - lokistacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loki.lightweight.com
  resources:
  - lokistacks/finalizers
  verbs:
  - update
- apiGroups:
  - loki.lightweight.com
  resources:
  - lokistacks/status
  verbs:
  - get
  - patch
  - update
