apiVersion: loki.lightweight.com/v1
kind: LokiStack
metadata:
  name: lokistack-dev
spec:
  size: 1x.small
  storage:
    schemas:
      - version: v13
        effectiveDate: 2023-10-15
    secret:
      name: test
      type: s3
  storageClassName: gp2
